from youtube_searcher import search_youtube

query = "Rob Zombie"
data = search_youtube(query)

"""
{'featured_channel': {'title': 'robzombie',
                      'videos': [{'length': '0:51',
                                  'length_human': '0 minutos e 51 segundos',
                                  'thumbnails': [{'height': 202,
                                                  'url': 'https://i.ytimg.com/vi/aQxaGpJNfyA/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBlD-Yl_nt_hT9fBxDFhF1BOYQb7Q',
                                                  'width': 360},
                                                 {'height': 404,
                                                  'url': 'https://i.ytimg.com/vi/aQxaGpJNfyA/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBoOvNMVcNn0ulgXbinINSZZRJ8yw',
                                                  'width': 720}],
                                  'title': 'Rob Zombie’s Three From Hell - '
                                           'Teaser Trailer',
                                  'url': 'https://www.youtube.com/watch?v=aQxaGpJNfyA',
                                  'videoId': 'aQxaGpJNfyA'},
                                 {'length': '0:13',
                                  'length_human': '0 minutos e 13 segundos',
                                  'thumbnails': [{'height': 270,
                                                  'url': 'https://i.ytimg.com/vi/fGLjQCY3xB8/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLARMovBDGRnbs3E0oevpN1DZdloTw',
                                                  'width': 480}],
                                  'title': 'Twins of Evil - Hell Never Dies '
                                           'Tour 2019',
                                  'url': 'https://www.youtube.com/watch?v=fGLjQCY3xB8',
                                  'videoId': 'fGLjQCY3xB8'},
                                 {'length': '4:14',
                                  'length_human': '4 minutos e 14 segundos',
                                  'thumbnails': [{'height': 202,
                                                  'url': 'https://i.ytimg.com/vi/roEzVi7pU5E/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLD-kjOc4xK8AXWJmU90g3aQ79xuvA',
                                                  'width': 360},
                                                 {'height': 404,
                                                  'url': 'https://i.ytimg.com/vi/roEzVi7pU5E/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLB73CYPN8BL9yq2klqdW4-eLb3L0g',
                                                  'width': 720}],
                                  'title': 'Rob Zombie & Marilyn Manson '
                                           'Discuss The First Time They Heard '
                                           "Each Other's Music",
                                  'url': 'https://www.youtube.com/watch?v=roEzVi7pU5E',
                                  'videoId': 'roEzVi7pU5E'},
                                 {'length': '2:58',
                                  'length_human': '2 minutos e 58 segundos',
                                  'thumbnails': [{'height': 202,
                                                  'url': 'https://i.ytimg.com/vi/FruOhKwrhvE/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDer5TP0kDNM-Pt_bm8hGglpu-uOg',
                                                  'width': 360},
                                                 {'height': 404,
                                                  'url': 'https://i.ytimg.com/vi/FruOhKwrhvE/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBuVm0QjtNWls-1CQaYCmZqpwTvCA',
                                                  'width': 720}],
                                  'title': 'Twins of Evil Tour – The Second '
                                           'Coming',
                                  'url': 'https://www.youtube.com/watch?v=FruOhKwrhvE',
                                  'videoId': 'FruOhKwrhvE'},
                                 {'length': '0:28',
                                  'length_human': '0 minutos e 28 segundos',
                                  'thumbnails': [{'height': 202,
                                                  'url': 'https://i.ytimg.com/vi/RGz9PwzWpHs/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAJVhJVTKjCTwnfqE2j-bgPj5ddQw',
                                                  'width': 360},
                                                 {'height': 404,
                                                  'url': 'https://i.ytimg.com/vi/RGz9PwzWpHs/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLB79PNpaYraOHnadlbCyXIf5HB1xg',
                                                  'width': 720}],
                                  'title': 'Rob Zombie - ASTRO-CREEP: 2000 '
                                           'LIVE - OUT NOW!',
                                  'url': 'https://www.youtube.com/watch?v=RGz9PwzWpHs',
                                  'videoId': 'RGz9PwzWpHs'},
                                 {'length': '0:29',
                                  'length_human': '0 minutos e 29 segundos',
                                  'thumbnails': [{'height': 202,
                                                  'url': 'https://i.ytimg.com/vi/fLpbovD_0bM/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAHyJOWLPdvYTCTNyrf8gNKh8Y5PA',
                                                  'width': 360},
                                                 {'height': 404,
                                                  'url': 'https://i.ytimg.com/vi/fLpbovD_0bM/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBEnZ6i7EStjZDVh4KFupyzgfsPRw',
                                                  'width': 720}],
                                  'title': 'Rob Zombie - Vinyl Catalog - '
                                           'Available Now!',
                                  'url': 'https://www.youtube.com/watch?v=fLpbovD_0bM',
                                  'videoId': 'fLpbovD_0bM'},
                                 {'length': '0:31',
                                  'length_human': '0 minutos e 31 segundos',
                                  'thumbnails': [{'height': 202,
                                                  'url': 'https://i.ytimg.com/vi/DcokDm5O-lM/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLA-tq7qYf0NRb3SS62LIZrk_1W_cQ',
                                                  'width': 360},
                                                 {'height': 404,
                                                  'url': 'https://i.ytimg.com/vi/DcokDm5O-lM/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCyJc0C2Yj6EMNquuaK_NrOVMtI3w',
                                                  'width': 720}],
                                  'title': 'Rob Zombie Career Vinyl Box - OUT '
                                           'NOW!',
                                  'url': 'https://www.youtube.com/watch?v=DcokDm5O-lM',
                                  'videoId': 'DcokDm5O-lM'},
                                 {'length': '1:43',
                                  'length_human': '1 minuto e 43 segundos',
                                  'thumbnails': [{'height': 202,
                                                  'url': 'https://i.ytimg.com/vi/qxSHmr4JbV0/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCHLtT_AR-9Iv3QBMr8l_lCSUPKcw',
                                                  'width': 360},
                                                 {'height': 404,
                                                  'url': 'https://i.ytimg.com/vi/qxSHmr4JbV0/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAp1fD6BRUuhgUVJtIpQFAqbfdfZg',
                                                  'width': 720}],
                                  'title': 'Rob Zombie Career Vinyl Box Set - '
                                           'OUT NOW!',
                                  'url': 'https://www.youtube.com/watch?v=qxSHmr4JbV0',
                                  'videoId': 'qxSHmr4JbV0'},
                                 {'length': '0:28',
                                  'length_human': '0 minutos e 28 segundos',
                                  'thumbnails': [{'height': 202,
                                                  'url': 'https://i.ytimg.com/vi/S4tS-MaHEgc/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCN5nbDDi5-lcBUH3odwLKut2X78Q',
                                                  'width': 360},
                                                 {'height': 404,
                                                  'url': 'https://i.ytimg.com/vi/S4tS-MaHEgc/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCqxAwVPHXWh87S8b99uyL7JTvxZg',
                                                  'width': 720}],
                                  'title': 'Rob Zombie - ASTRO-CREEP: 2000 '
                                           'LIVE - Available March 30',
                                  'url': 'https://www.youtube.com/watch?v=S4tS-MaHEgc',
                                  'videoId': 'S4tS-MaHEgc'},
                                 {'length': '0:29',
                                  'length_human': '0 minutos e 29 segundos',
                                  'thumbnails': [{'height': 202,
                                                  'url': 'https://i.ytimg.com/vi/gGwDRAtHwow/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCJZvpxtz6XG7GohqfWqzOEPvmwKg',
                                                  'width': 360},
                                                 {'height': 404,
                                                  'url': 'https://i.ytimg.com/vi/gGwDRAtHwow/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBKhD8qjakLARzNZTys0fHyTzB9uA',
                                                  'width': 720}],
                                  'title': 'Rob Zombie - Vinyl Catalog - '
                                           'Available March 30',
                                  'url': 'https://www.youtube.com/watch?v=gGwDRAtHwow',
                                  'videoId': 'gGwDRAtHwow'}]},
 'playlists': [{'playlistId': 'PL9E5EE14539AE3644',
                'title': 'rob zombie playlist',
                'url': 'https://www.youtube.com/watch?v=lxAOc4JYELc&list=PL9E5EE14539AE3644',
                'videoId': 'lxAOc4JYELc'}],
 'related_queries': [{'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/ekC4dHtXghjh-iLwA947TaD4iRJoV7DcxPKeKshRX3y1kt_6hr8skBDhCUQXCONLfjkm60dDnZdC7Qpe=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'marilyn manson',
                      'url': 'https://www.youtube.com/results?search_query=marilyn+manson&sp=Eh-SARwKCi9tLzAzaDUwMmsqDm1hcmlseW4gbWFuc29ueAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/ydf-77N5ZOaL39t57-bd0cby7qILKibyjnU2ma1b1xk9DDqLOw_2WqjymTmFJx9LSVQRSs2eQPc6IHNN=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'powerman 5000',
                      'url': 'https://www.youtube.com/results?search_query=powerman+5000&sp=Eh2SARoKCS9tLzAxNTQ5eCoNcG93ZXJtYW4gNTAwMHgB'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/JVofoNggGyrfCgKRyEB1u6J1MfBZq01mwklJkKJfzEpjfvRtIShxFDoKyWlAI2QSKvPrsZlZcRwcl8g=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'alice cooper',
                      'url': 'https://www.youtube.com/results?search_query=alice+cooper&sp=EhySARkKCS9tLzAxMWhkbioMYWxpY2UgY29vcGVyeAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/uK_6CwgagId0aKKkg1RTjEuGQDo1eUhie9N-RR1tfsjXGRWuKlvW7CCywrtsy0KMDqfUqGBx7OROZNI=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'white zombie',
                      'url': 'https://www.youtube.com/results?search_query=white+zombie&sp=EhySARkKCS9tLzA1Z2dwZioMd2hpdGUgem9tYmlleAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/uJlYoL5XPVCi32Qxqptx6RMfPEk-J67BtjU-cbnIEvaYYqZ1NgP-sZZfNAIV-ZBTgb9KpGmkjZDHY3s=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'john carpenter',
                      'url': 'https://www.youtube.com/results?search_query=john+carpenter&sp=Eh2SARoKCC9tLzBkcjV5Kg5qb2huIGNhcnBlbnRlcngB'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/4CYt4ULmbYYP0J4szNMXgyIotQD5gNrNQzaX4CZf4W76-dYEOWSYwVPRqtkO1DEPr_G6puHBenYtcQQ=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'slipknot',
                      'url': 'https://www.youtube.com/results?search_query=slipknot&sp=EheSARQKCC9tLzBudHE3KghzbGlwa25vdHgB'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/kxqSK6Yt9MunUR-fgsoqo2J4fjf4BpPDoAjBXS8QrvJaaVBMYP5TeYnaaEOOBaTKlfKlIOSJUTVJSnU=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'babymetal',
                      'url': 'https://www.youtube.com/results?search_query=babymetal&sp=EhqSARcKCi9tLzBxNTdtMmYqCWJhYnltZXRhbHgB'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/qKUqNV8FpS5F1MHcG02KSeuAt_4x0XBezv5zpkQYpIMxK0FiGejB0TKJHgu_tfXGCbaVxodtXg=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'godsmack',
                      'url': 'https://www.youtube.com/results?search_query=godsmack&sp=EhiSARUKCS9tLzAxNjNqXyoIZ29kc21hY2t4AQ%253D%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/TbLnMOoZTmsrVB0J2zpUfJGgYmjOE1xmCJ55LUuX02qlMET3CMxe527vEjo4z2miU99xh9ih8aMs9v4=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'korn',
                      'url': 'https://www.youtube.com/results?search_query=korn&sp=EhOSARAKCC9tLzBjOWwxKgRrb3JueAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/gGnVSqeNBa_4NBsdCU4Kth1ys9IaYksP7zJ5Z3NibAUl-WCBiP8WRB2MkeT7rtm0-Or7W3yUznFJZt0=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'ozzy osbourne',
                      'url': 'https://www.youtube.com/results?search_query=ozzy+osbourne&sp=Eh6SARsKCi9tLzAxdnRxbWwqDW96enkgb3Nib3VybmV4AQ%253D%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/EGPOFCUL__GQlZRipF2G6xW2gtTS6I0RMzo4BRMXN999LkUivh1tCqjChl_ozt307Tsr7zkr_EO_BV4=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'rammstein',
                      'url': 'https://www.youtube.com/results?search_query=rammstein&sp=EhiSARUKCC9tLzA2ZGtfKglyYW1tc3RlaW54AQ%253D%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/MJiSBOuLgmEXR2uKfSAmJocgk5RKC51GDM211bm0Zss0_wKWH49vPjhC-080LohmIuiZgU4ZsLD95kA=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'nine inch nails',
                      'url': 'https://www.youtube.com/results?search_query=nine+inch+nails&sp=Eh6SARsKCC9tLzBqZzc3Kg9uaW5lIGluY2ggbmFpbHN4AQ%253D%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/A9uFtKF_cP6Lxm_cOBz_9cbKuqghdKNbhndjN6al43Efib0vAHgro8Tr3xNN-JUI_kqy8ZMaDhKFG80=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'seether',
                      'url': 'https://www.youtube.com/results?search_query=seether&sp=EheSARQKCS9tLzAzdjh6MCoHc2VldGhlcngB'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/KnByTUXJkfrqlDoS4LXhyRFZALhxmHOfBtI9FLHtb1g5OB5msMdHXHcISvwtQGNtzwXKqjDmIw=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'metallica',
                      'url': 'https://www.youtube.com/results?search_query=metallica&sp=EhiSARUKCC9tLzA0cmNyKgltZXRhbGxpY2F4AQ%253D%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/5vCBYw9OHEcltx6D_ygjpVtBlqfWpvY1tCA1hgTJUNP-SlDTUWwW4Tr4cJfR34lSxzapv0JbDh6Pvko=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'miley cyrus',
                      'url': 'https://www.youtube.com/results?search_query=miley+cyrus&sp=EhuSARgKCS9tLzBiZHhzNSoLbWlsZXkgY3lydXN4AQ%253D%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/jHvXEDZAKcWzXjVIF_xGMJn-gGsL1CbALWF31US9DvffCDg0Dc-cTVM1MPobNoSroscgbZ1Ck7Nn58ML=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'danielle harris',
                      'url': 'https://www.youtube.com/results?search_query=danielle+harris&sp=Eh-SARwKCS9tLzAyZ3lsdioPZGFuaWVsbGUgaGFycmlzeAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/4VCgYmM-P1BCyd7Ty-L2zBL6S4Gl4gLR3Ai1zF342MxzvGpxiIY2G8Qfa1Ux4jR1s6yZXxZmWb-FTXg=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'trent reznor',
                      'url': 'https://www.youtube.com/results?search_query=trent+reznor&sp=EhySARkKCS9tLzAxMjcxaCoMdHJlbnQgcmV6bm9yeAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/uxu1UtS0Kzs7myqsJDyQIjiGgzXO03EfKolghtNTKjTsoUs6JqmCDMoEXb9nPPMS_UHiCY7MYmvH3do=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'zakk wylde',
                      'url': 'https://www.youtube.com/results?search_query=zakk+wylde&sp=EhuSARgKCi9tLzAxd2dyN3QqCnpha2sgd3lsZGV4AQ%253D%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/IlNp_o9GKakp7qtaDAKaDxpW29qtP8sjqQXPcBQ9uAdOUU3AnJdB85xLRiYIGT3FlCmobm6oiMQX4GU=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'ac dc',
                      'url': 'https://www.youtube.com/results?search_query=ac+dc&sp=EhWSARIKCS9tLzAxMzRzNSoFYWMgZGN4AQ%253D%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/ynviWLO4w39ZLIPpwFQZUTUL1XuHXVRpkdjOInB0dR80-eWWJIyAanQXmoIFXHLrIU4rnLitiwaNBw=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'red hot chili peppers',
                      'url': 'https://www.youtube.com/results?search_query=red+hot+chili+peppers&sp=EiSSASEKCC9tLzA2bWo0KhVyZWQgaG90IGNoaWxpIHBlcHBlcnN4AQ%253D%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/3733Vu3lYU5XY_Mzk1VpsVVC8g2-qfiz4yygxpge-w4lsYhCG73ahvH0Ng989tC4gO8KpKuz_g=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'motley crue',
                      'url': 'https://www.youtube.com/results?search_query=motley+crue&sp=EhqSARcKCC9tLzA0eDczKgttb3RsZXkgY3J1ZXgB'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/vtdkFSDCcM-E5FGhxSkfrrUDmTNi0CZsJ6nwHSD2c9huoAWaasTVIIa0ahnqLq6yKYyv2a4fy5r_Y5E=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'limp bizkit',
                      'url': 'https://www.youtube.com/results?search_query=limp+bizkit&sp=EhqSARcKCC9tLzA0cXptKgtsaW1wIGJpemtpdHgB'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/PdJbECdGO2tMXmEwlEq2kS-0nWANDKOc3p9QRG3-frcaJzScGfiKRYcIZXVDSozd80K-YhEC9QpvqYg=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'megadeth',
                      'url': 'https://www.youtube.com/results?search_query=megadeth&sp=EheSARQKCC9tLzA1NjB3KghtZWdhZGV0aHgB'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/EnQ-SSg3TcUzQ-BemUoLDhEf0jH0A2mbJ7pOSsaUh7XnTpOPecbVSlGiv62pN6YCghKNMiKoLnEsKpsj=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'corey taylor',
                      'url': 'https://www.youtube.com/results?search_query=corey+taylor&sp=Eh2SARoKCi9tLzAxdHR2eGMqDGNvcmV5IHRheWxvcngB'},
                     {'thumbnails': [{'height': 180,
                                      'url': 'https://lh3.googleusercontent.com/pFq_Rv7pYrZbrnFhI5NIexZaL6jWfUIUa-4bdQYOovSE5Kk9FCcd1GauukMY4J8PkZJj_q30zc48DA=w320-h180-p-k-c0x00ffffff-no-rj-mo',
                                      'width': 320}],
                      'title': 'static x',
                      'url': 'https://www.youtube.com/results?search_query=static+x&sp=EhiSARUKCS9tLzAxNTE4OSoIc3RhdGljIHh4AQ%253D%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/KDLeJ5Rasuo/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'rob zombie interview',
                      'url': 'https://www.youtube.com/results?search_query=rob+zombie+interview&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/NsZKpKmG5WI/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'rob zombie reaction',
                      'url': 'https://www.youtube.com/results?search_query=rob+zombie+reaction&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/Z0dA3h05EBQ/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'rob zombie lyrics',
                      'url': 'https://www.youtube.com/results?search_query=rob+zombie+lyrics&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/TLJYyEfuhDE/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'rob zombie american nightmare',
                      'url': 'https://www.youtube.com/results?search_query=rob+zombie+american+nightmare&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/iFQ9-JEOQVo/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'rob zombie remix',
                      'url': 'https://www.youtube.com/results?search_query=rob+zombie+remix&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/0698sTH7mUk/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'my durango rob zombie',
                      'url': 'https://www.youtube.com/results?search_query=my+durango+rob+zombie&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/X99tV3185bA/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'rob zombie babymetal',
                      'url': 'https://www.youtube.com/results?search_query=rob+zombie+babymetal&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/mjINW3pzvaE/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'rob zombie cribs',
                      'url': 'https://www.youtube.com/results?search_query=rob+zombie+cribs&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/KDLeJ5Rasuo/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'rob zombie documentary',
                      'url': 'https://www.youtube.com/results?search_query=rob+zombie+documentary&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/dEUCYUhOg3U/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'rob zombie concert',
                      'url': 'https://www.youtube.com/results?search_query=rob+zombie+concert&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/0698sTH7mUk/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'edge rob zombie theme',
                      'url': 'https://www.youtube.com/results?search_query=edge+rob+zombie+theme&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/oz8eeQXsT7Q/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'rob zombie radio lyrics',
                      'url': 'https://www.youtube.com/results?search_query=rob+zombie+radio+lyrics&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/jtW4PIQmSGI/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'rob zombie wife',
                      'url': 'https://www.youtube.com/results?search_query=rob+zombie+wife&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/SJsqgVag_2s/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'rob zombie 2020',
                      'url': 'https://www.youtube.com/results?search_query=rob+zombie+2020&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/LjJY8Z43LqQ/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'devilman rob zombie',
                      'url': 'https://www.youtube.com/results?search_query=devilman+rob+zombie&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/h2WDBBRetfE/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'rob zombie marilyn manson',
                      'url': 'https://www.youtube.com/results?search_query=rob+zombie+marilyn+manson&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/J59au6_kXH8/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'rob zombie topic',
                      'url': 'https://www.youtube.com/results?search_query=rob+zombie+topic&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/6DqLVfxM-NE/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'ironhead rob zombie ozzy',
                      'url': 'https://www.youtube.com/results?search_query=ironhead+rob+zombie+ozzy&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/-uWqiDIZJ4U/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'rob zombie blacktop rolling',
                      'url': 'https://www.youtube.com/results?search_query=rob+zombie+blacktop+rolling&sp=eAE%253D'}],
 'related_videos': [{'length': '5:03',
                     'length_human': '5 minutos e 3 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 202,
                                     'url': 'https://i.ytimg.com/vi/5abamRO41fE/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBJwXXKMfD_IQZR485izC1N0oc9Ig',
                                     'width': 360},
                                    {'height': 404,
                                     'url': 'https://i.ytimg.com/vi/5abamRO41fE/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAdxi_yl0TJG3vugoYMNrV_smJczA',
                                     'width': 720}],
                     'title': 'Slipknot - Psychosocial [OFFICIAL VIDEO]',
                     'url': 'https://www.youtube.com/watch?v=5abamRO41fE',
                     'videoId': '5abamRO41fE'},
                    {'length': '4:04',
                     'length_human': '4 minutos e 4 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 270,
                                     'url': 'https://i.ytimg.com/vi/K5jvUXij7nU/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAWGQs6Mg4XKzDDReg74BM3ZLQ6qg',
                                     'width': 480}],
                     'title': 'Megadeth - Symphony of Destruction (Studio '
                              'Version)',
                     'url': 'https://www.youtube.com/watch?v=K5jvUXij7nU',
                     'videoId': 'K5jvUXij7nU'},
                    {'length': '3:56',
                     'length_human': '3 minutos e 56 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 202,
                                     'url': 'https://i.ytimg.com/vi/W3q8Od5qJio/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLB9Ocj9cdiwOXjEmU6tcjbcP3k7aQ',
                                     'width': 360},
                                    {'height': 404,
                                     'url': 'https://i.ytimg.com/vi/W3q8Od5qJio/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBIPKV8jhv2OMGHqF8LS1mnUojfDg',
                                     'width': 720}],
                     'title': 'Rammstein - Du Hast (Official Video)',
                     'url': 'https://www.youtube.com/watch?v=W3q8Od5qJio',
                     'videoId': 'W3q8Od5qJio'},
                    {'length': '4:39',
                     'length_human': '4 minutos e 39 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 270,
                                     'url': 'https://i.ytimg.com/vi/L78yVFeyvRo/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAlm80k0zkQZOVX0sXsGSwsSC-Htg',
                                     'width': 480}],
                     'title': 'Disturbed - down with the sickness',
                     'url': 'https://www.youtube.com/watch?v=L78yVFeyvRo',
                     'videoId': 'L78yVFeyvRo'},
                    {'length': '4:27',
                     'length_human': '4 minutos e 27 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 202,
                                     'url': 'https://i.ytimg.com/vi/jRGrNDV2mKc/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCRIQeH_8N7TcBMDjo_PYB7LKCazw',
                                     'width': 360},
                                    {'height': 404,
                                     'url': 'https://i.ytimg.com/vi/jRGrNDV2mKc/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLB3KY_FmQMymhFp7OIpvdOqZoqMqw',
                                     'width': 720}],
                     'title': 'Korn - Freak On a Leash (AC3 Stereo) (Official '
                              'Music Video)',
                     'url': 'https://www.youtube.com/watch?v=jRGrNDV2mKc',
                     'videoId': 'jRGrNDV2mKc'},
                    {'length': '2:36',
                     'length_human': '2 minutos e 36 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 270,
                                     'url': 'https://i.ytimg.com/vi/Ps0MfBG5-Uo/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCL8yJkR1nF59wvyveYowY2wD2k6g',
                                     'width': 480}],
                     'title': 'Static-X - Push It (Video)',
                     'url': 'https://www.youtube.com/watch?v=Ps0MfBG5-Uo',
                     'videoId': 'Ps0MfBG5-Uo'},
                    {'length': '6:29',
                     'length_human': '6 minutos e 29 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 270,
                                     'url': 'https://i.ytimg.com/vi/vlK8EdDkdEg/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLA67mHKHNs5qIkwh1HwcW98Ljs89g',
                                     'width': 480}],
                     'title': 'Rob Zombie-House of a 1000 Corpses Song',
                     'url': 'https://www.youtube.com/watch?v=vlK8EdDkdEg',
                     'videoId': 'vlK8EdDkdEg'},
                    {'length': '4:05',
                     'length_human': '4 minutos e 5 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 270,
                                     'url': 'https://i.ytimg.com/vi/7SSDZHZHYvM/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBnQ3MnFxC7oMA6xA9Hv3rTtFOs6Q',
                                     'width': 480}],
                     'title': 'Rob Zombie - Demon Speeding',
                     'url': 'https://www.youtube.com/watch?v=7SSDZHZHYvM',
                     'videoId': '7SSDZHZHYvM'},
                    {'length': '3:46',
                     'length_human': '3 minutos e 46 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 270,
                                     'url': 'https://i.ytimg.com/vi/njloMiAWlrc/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAtDKxulDdQjRzaKSniy6Cw0dBNVw',
                                     'width': 480}],
                     'title': 'Rob Zombie - Mars Needs Women [OFFICIAL VIDEO]',
                     'url': 'https://www.youtube.com/watch?v=njloMiAWlrc',
                     'videoId': 'njloMiAWlrc'},
                    {'length': '4:12',
                     'length_human': '4 minutos e 12 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 202,
                                     'url': 'https://i.ytimg.com/vi/kgltKEKw_wA/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBUEPTY7_wCJeu9NuddTuEv9-IEQg',
                                     'width': 360},
                                    {'height': 404,
                                     'url': 'https://i.ytimg.com/vi/kgltKEKw_wA/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLC5BrBbX-m7c8ecY83X6sgvXtiSbg',
                                     'width': 720}],
                     'title': 'Rob Zombie - Ging Gang Gong De Do Gong De Laga '
                              'Raga (Audio / Live)',
                     'url': 'https://www.youtube.com/watch?v=kgltKEKw_wA',
                     'videoId': 'kgltKEKw_wA'}],
 'videos': [{'length': '3:49',
             'length_human': '3 minutos e 49 segundos',
             'thumbnails': [{'height': 202,
                             'url': 'https://i.ytimg.com/vi/EqQuihD0hoI/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCm8RcNcTePxiGFrq2Uh3VBvmTs9g',
                             'width': 360},
                            {'height': 404,
                             'url': 'https://i.ytimg.com/vi/EqQuihD0hoI/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCZFTsF5LwedXNbjdb2LgSGyc6krA',
                             'width': 720}],
             'title': 'Rob Zombie - Dragula (Official Video)',
             'url': 'https://www.youtube.com/watch?v=EqQuihD0hoI',
             'videoId': 'EqQuihD0hoI'},
            {'length': '3:32',
             'length_human': '3 minutos e 32 segundos',
             'thumbnails': [{'height': 202,
                             'url': 'https://i.ytimg.com/vi/ey-AmU6Nbgk/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDAFkhYbZhGoY3-Ec070Zo7--wsWQ',
                             'width': 360},
                            {'height': 404,
                             'url': 'https://i.ytimg.com/vi/ey-AmU6Nbgk/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDEYo5CaH_-1oGg5qHLLXvrHhkW1g',
                             'width': 720}],
             'title': 'Rob Zombie - Dead City Radio And The New Gods Of '
                      'Supertown',
             'url': 'https://www.youtube.com/watch?v=ey-AmU6Nbgk',
             'videoId': 'ey-AmU6Nbgk'},
            {'length': '3:24',
             'length_human': '3 minutos e 24 segundos',
             'thumbnails': [{'height': 202,
                             'url': 'https://i.ytimg.com/vi/BvsMPOfblfg/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBy7iE9-zgeczuBkZzwabA-Avb-cw',
                             'width': 360},
                            {'height': 404,
                             'url': 'https://i.ytimg.com/vi/BvsMPOfblfg/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDn8QT3octXXqf4-z2O1pUYWOkOfw',
                             'width': 720}],
             'title': 'Rob Zombie - Living Dead Girl (Official Video)',
             'url': 'https://www.youtube.com/watch?v=BvsMPOfblfg',
             'videoId': 'BvsMPOfblfg'},
            {'length': '3:39',
             'length_human': '3 minutos e 39 segundos',
             'thumbnails': [{'height': 202,
                             'url': 'https://i.ytimg.com/vi/VK16w_Esrno/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDZpxVCAQPUUPh1iH1Sjz_ArBSe0g',
                             'width': 360},
                            {'height': 404,
                             'url': 'https://i.ytimg.com/vi/VK16w_Esrno/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBIghAp-LMn93RlD-9LOof0vall7w',
                             'width': 720}],
             'title': 'Rob Zombie - Feel So Numb',
             'url': 'https://www.youtube.com/watch?v=VK16w_Esrno',
             'videoId': 'VK16w_Esrno'},
            {'length': '3:42',
             'length_human': '3 minutos e 42 segundos',
             'thumbnails': [{'height': 202,
                             'url': 'https://i.ytimg.com/vi/uHBtpqbOKXk/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAID1e7bmmoGwTDgrvJ2_V4cud-Mw',
                             'width': 360},
                            {'height': 404,
                             'url': 'https://i.ytimg.com/vi/uHBtpqbOKXk/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDRMbXVlh6zyZa5_mIL7Fo0GAN7OA',
                             'width': 720}],
             'title': 'Rob Zombie - Superbeast (Official Video)',
             'url': 'https://www.youtube.com/watch?v=uHBtpqbOKXk',
             'videoId': 'uHBtpqbOKXk'},
            {'length': '3:12',
             'length_human': '3 minutos e 12 segundos',
             'thumbnails': [{'height': 202,
                             'url': 'https://i.ytimg.com/vi/0698sTH7mUk/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLC-gxlztlj8DrhjZieMSOPqgcBsvw',
                             'width': 360},
                            {'height': 404,
                             'url': 'https://i.ytimg.com/vi/0698sTH7mUk/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAVSGrxnZ_HUSqwz_h9Klg4H4ZnWw',
                             'width': 720}],
             'title': 'Rob Zombie - Never Gonna Stop (The Red Red Kroovy) '
                      '[Official Video]',
             'url': 'https://www.youtube.com/watch?v=0698sTH7mUk',
             'videoId': '0698sTH7mUk'},
            {'length': '3:57',
             'length_human': '3 minutos e 57 segundos',
             'thumbnails': [{'height': 202,
                             'url': 'https://i.ytimg.com/vi/yPNFVj-pISU/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLD8oBlGm_xaQpw3hYGAdmaSx53huw',
                             'width': 360},
                            {'height': 404,
                             'url': 'https://i.ytimg.com/vi/yPNFVj-pISU/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCKcWd8pp71kKOcHtpQibScXY2vDQ',
                             'width': 720}],
             'title': "White Zombie - Thunder Kiss '65 (Official Video)",
             'url': 'https://www.youtube.com/watch?v=yPNFVj-pISU',
             'videoId': 'yPNFVj-pISU'},
            {'length': '3:41',
             'length_human': '3 minutos e 41 segundos',
             'thumbnails': [{'height': 270,
                             'url': 'https://i.ytimg.com/vi/AeUwikDrA9I/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLA7Te26pSBxK0VHDR0g6HGPXQytNw',
                             'width': 480}],
             'title': 'Rob Zombie - Sick Bubblegum',
             'url': 'https://www.youtube.com/watch?v=AeUwikDrA9I',
             'videoId': 'AeUwikDrA9I'},
            {'length': '5:12',
             'length_human': '5 minutos e 12 segundos',
             'thumbnails': [{'height': 202,
                             'url': 'https://i.ytimg.com/vi/bXvTk-N0HKo/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBtm0Zb_6PzCUCZ4IkidxKHiwwiuA',
                             'width': 360},
                            {'height': 404,
                             'url': 'https://i.ytimg.com/vi/bXvTk-N0HKo/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCH58yvIQozzyFpaOYv2QSXLZ-Skw',
                             'width': 720}],
             'title': 'Rob Zombie - The Life And Times Of A Teenage Rock God',
             'url': 'https://www.youtube.com/watch?v=bXvTk-N0HKo',
             'videoId': 'bXvTk-N0HKo'},
            {'length': '3:28',
             'length_human': '3 minutos e 28 segundos',
             'thumbnails': [{'height': 202,
                             'url': 'https://i.ytimg.com/vi/MdKXShP_oc4/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDKM-MrwOgxQ-mF1GCskH7n6dqgtA',
                             'width': 360},
                            {'height': 404,
                             'url': 'https://i.ytimg.com/vi/MdKXShP_oc4/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAfyyId49PkwyOUFMetBOptCxifYA',
                             'width': 720}],
             'title': 'Rob Zombie - American Witch',
             'url': 'https://www.youtube.com/watch?v=MdKXShP_oc4',
             'videoId': 'MdKXShP_oc4'},
            {'length': '3:38',
             'length_human': '3 minutos e 38 segundos',
             'thumbnails': [{'height': 202,
                             'url': 'https://i.ytimg.com/vi/vV0NoICl7cE/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCQEc648sLhn2vYqbjbdEdqScnhPw',
                             'width': 360},
                            {'height': 404,
                             'url': 'https://i.ytimg.com/vi/vV0NoICl7cE/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCDDyNDWSqAuNZXtzHVaNP-IvXzWQ',
                             'width': 720}],
             'title': 'Rob Zombie - Lords Of Salem',
             'url': 'https://www.youtube.com/watch?v=vV0NoICl7cE',
             'videoId': 'vV0NoICl7cE'},
            {'length': '3:36',
             'length_human': '3 minutos e 36 segundos',
             'thumbnails': [{'height': 202,
                             'url': 'https://i.ytimg.com/vi/Wzlky9Klu4I/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDSrxKghB3xHhXgQQD9Zz7Fr1V62g',
                             'width': 360},
                            {'height': 404,
                             'url': 'https://i.ytimg.com/vi/Wzlky9Klu4I/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBkzVxeI81l8aEsg8TXYCYp7N_2tw',
                             'width': 720}],
             'title': "Rob Zombie - We're An American Band",
             'url': 'https://www.youtube.com/watch?v=Wzlky9Klu4I',
             'videoId': 'Wzlky9Klu4I'},
            {'length': '3:47',
             'length_human': '3 minutos e 47 segundos',
             'thumbnails': [{'height': 202,
                             'url': 'https://i.ytimg.com/vi/0viDab5XSRg/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLD5EoV-wauF3XHyvgxIPZVcTatP-Q',
                             'width': 360},
                            {'height': 404,
                             'url': 'https://i.ytimg.com/vi/0viDab5XSRg/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBfIX242PO15Ey-phkLfkyz6fy6MQ',
                             'width': 720}],
             'title': 'ROB ZOMBIE - Sick Bubblegum (Official Video)',
             'url': 'https://www.youtube.com/watch?v=0viDab5XSRg',
             'videoId': '0viDab5XSRg'},
            {'length': '4:03',
             'length_human': '4 minutos e 3 segundos',
             'thumbnails': [{'height': 202,
                             'url': 'https://i.ytimg.com/vi/AzJEpch-i6A/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBVm14s5trx-5QWgnkpl3v3dUyJcw',
                             'width': 360},
                            {'height': 404,
                             'url': 'https://i.ytimg.com/vi/AzJEpch-i6A/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLB5IEiRnuTMfrvuxAQLw8faoMhmhA',
                             'width': 720}],
             'title': 'Rob Zombie - Demonoid Phenomenon',
             'url': 'https://www.youtube.com/watch?v=AzJEpch-i6A',
             'videoId': 'AzJEpch-i6A'},
            {'length': '2:06:02',
             'length_human': '2 horas, 6 minutos e 2 segundos',
             'thumbnails': [{'height': 270,
                             'url': 'https://i.ytimg.com/vi/KDLeJ5Rasuo/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBAHfgTqL47dZjPfCHJngKmUOJupA',
                             'width': 480}],
             'title': 'Joe Rogan Experience #1353 - Rob Zombie',
             'url': 'https://www.youtube.com/watch?v=KDLeJ5Rasuo',
             'videoId': 'KDLeJ5Rasuo'},
            {'length': '3:28',
             'length_human': '3 minutos e 28 segundos',
             'thumbnails': [{'height': 202,
                             'url': 'https://i.ytimg.com/vi/NJZtUiX-FUE/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDsqPEOuVAcXuiIfLLNL5M17zV4-w',
                             'width': 360},
                            {'height': 404,
                             'url': 'https://i.ytimg.com/vi/NJZtUiX-FUE/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDoH-Ze22_8g9JS1XDUEFxtvGGnbw',
                             'width': 720}],
             'title': 'Rob Zombie - American Witch',
             'url': 'https://www.youtube.com/watch?v=NJZtUiX-FUE',
             'videoId': 'NJZtUiX-FUE'},
            {'length': '2:18',
             'length_human': '2 minutos e 18 segundos',
             'thumbnails': [{'height': 202,
                             'url': 'https://i.ytimg.com/vi/FVN6CDo02gA/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLD7NT2rahJijDw_auqMGFhTZ8y1Yg',
                             'width': 360},
                            {'height': 404,
                             'url': 'https://i.ytimg.com/vi/FVN6CDo02gA/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLA9pqOh8m0lhTF_vFHhEjrhnYaLNw',
                             'width': 720}],
             'title': 'Rob Zombie - Get High',
             'url': 'https://www.youtube.com/watch?v=FVN6CDo02gA',
             'videoId': 'FVN6CDo02gA'}]}
"""

query = "Space Rock Mix"
data = search_youtube(query)


"""
{'featured_channel': {'videos': []},
 'playlists': [{'playlistId': 'PLdidg0e7YRAeYx9G7SRXGx-m7VIZrM3vL',
                'title': 'PSYCHEDELIC / STONER & SPACE ROCK PLAYLIST',
                'url': 'https://www.youtube.com/watch?v=QqYcJi7EiNc&list=PLdidg0e7YRAeYx9G7SRXGx-m7VIZrM3vL',
                'videoId': 'QqYcJi7EiNc'},
               {'playlistId': 'PLKudVNYkaYRjcbYAjmtgiTQD68motcudB',
                'title': 'Instrumental Psychedelic/Stoner/Space Rock Full '
                         'Album Playlist',
                'url': 'https://www.youtube.com/watch?v=nFTCGS2aZtA&list=PLKudVNYkaYRjcbYAjmtgiTQD68motcudB',
                'videoId': 'nFTCGS2aZtA'}],
 'related_queries': [{'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/nchwoV9nWzE/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'psychedelic rock 2019',
                      'url': 'https://www.youtube.com/results?search_query=psychedelic+rock+2019&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/as1QfC2L0Og/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'stoner rock playlist',
                      'url': 'https://www.youtube.com/results?search_query=stoner+rock+playlist&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/_nw_OZfaIZ4/mqdefault.jpg',
                                      'width': 320}],
                      'title': '#highonmusic',
                      'url': 'https://www.youtube.com/results?search_query=%23highonmusic&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/UhGaGSJzR58/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'psychedelic guitar',
                      'url': 'https://www.youtube.com/results?search_query=psychedelic+guitar&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/Ke06X9fAWAU/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'spaceslug - proton lander',
                      'url': 'https://www.youtube.com/results?search_query=spaceslug+-+proton+lander&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/abisosOe0Y4/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'los natas brisa del desierto',
                      'url': 'https://www.youtube.com/results?search_query=los+natas+brisa+del+desierto&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/tmozGmGoJuw/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'psychedelic pop',
                      'url': 'https://www.youtube.com/results?search_query=psychedelic+pop&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/iuWa5wh8lG0/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'psychedelic songs',
                      'url': 'https://www.youtube.com/results?search_query=psychedelic+songs&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/QyQ_6qbsvnY/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'psychedelic video',
                      'url': 'https://www.youtube.com/results?search_query=psychedelic+video&sp=eAE%253D'},
                     {'thumbnails': [{'height': 180,
                                      'url': '//i.ytimg.com/vi/01H_9Ijh1Zk/mqdefault.jpg',
                                      'width': 320}],
                      'title': 'space metal',
                      'url': 'https://www.youtube.com/results?search_query=space+metal&sp=eAE%253D'}],
 'related_videos': [{'length': '54:36',
                     'length_human': '54 minutos e 36 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 94,
                                     'url': 'https://i.ytimg.com/vi/dHC7P400C6w/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDbhb0zmy0sl4kf7z4JXdtmbaDkjg',
                                     'width': 168},
                                    {'height': 110,
                                     'url': 'https://i.ytimg.com/vi/dHC7P400C6w/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLBB6VX8gRqJr13OmcCut5tQhFN4aA',
                                     'width': 196},
                                    {'height': 138,
                                     'url': 'https://i.ytimg.com/vi/dHC7P400C6w/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAuzQksv2mWRAC9xADiLB5iDGMcXg',
                                     'width': 246},
                                    {'height': 188,
                                     'url': 'https://i.ytimg.com/vi/dHC7P400C6w/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAJvCwrNid4SdFP3f8WjqReXKTG0A',
                                     'width': 336}],
                     'title': 'Paint the Sky Red - Not All Who Wonder Are Lost '
                              '(Full Album)',
                     'url': 'https://www.youtube.com/watch?v=dHC7P400C6w',
                     'videoId': 'dHC7P400C6w'},
                    {'length': '43:11',
                     'length_human': '43 minutos e 11 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 94,
                                     'url': 'https://i.ytimg.com/vi/-gXrS6eKfjk/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLBQuWt84-VCyB9FfMSfNTpi3j5jFQ',
                                     'width': 168},
                                    {'height': 110,
                                     'url': 'https://i.ytimg.com/vi/-gXrS6eKfjk/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLCHRK_oWbGb46NR9M1zDRrsiKSIWw',
                                     'width': 196},
                                    {'height': 138,
                                     'url': 'https://i.ytimg.com/vi/-gXrS6eKfjk/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCm7oawtXFxaMgo4R1GUWNdccEV0g',
                                     'width': 246},
                                    {'height': 188,
                                     'url': 'https://i.ytimg.com/vi/-gXrS6eKfjk/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAF7nzzPXQGpSyUSijG64GL-6CrNg',
                                     'width': 336}],
                     'title': 'The Sound Defects - The Iron Horse [Full album]',
                     'url': 'https://www.youtube.com/watch?v=-gXrS6eKfjk',
                     'videoId': '-gXrS6eKfjk'},
                    {'length': '44:28',
                     'length_human': '44 minutos e 28 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 94,
                                     'url': 'https://i.ytimg.com/vi/yhXHH2sZlQU/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLANtbcvvMjdKSt9twwfGKRzPyBv4w',
                                     'width': 168},
                                    {'height': 110,
                                     'url': 'https://i.ytimg.com/vi/yhXHH2sZlQU/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLD9DZ2ePulHquqVR_2i4V7s-X0k1w',
                                     'width': 196},
                                    {'height': 138,
                                     'url': 'https://i.ytimg.com/vi/yhXHH2sZlQU/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAKGwYKwK05QUEd9iHonr-Qgj_TmQ',
                                     'width': 246},
                                    {'height': 188,
                                     'url': 'https://i.ytimg.com/vi/yhXHH2sZlQU/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLB7rpZGEXCehc7N2s8DQPYtM68dlw',
                                     'width': 336}],
                     'title': 'GOD IS AN ASTRONAUT - All is Violent, All is '
                              'Bright [Full Album]',
                     'url': 'https://www.youtube.com/watch?v=yhXHH2sZlQU',
                     'videoId': 'yhXHH2sZlQU'},
                    {'length': '1:09:19',
                     'length_human': '1 hora, 9 minutos e 19 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 94,
                                     'url': 'https://i.ytimg.com/vi/lvCNqJCattk/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDgM6CM30S1OWL8YNUReXVVsqnEDw',
                                     'width': 168},
                                    {'height': 110,
                                     'url': 'https://i.ytimg.com/vi/lvCNqJCattk/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLCTYcFo8pLUuFNszGd6NOkXiH4WwQ',
                                     'width': 196},
                                    {'height': 138,
                                     'url': 'https://i.ytimg.com/vi/lvCNqJCattk/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLA0kSrnZ8_pbesHBjYF6CHoDPoK-A',
                                     'width': 246},
                                    {'height': 188,
                                     'url': 'https://i.ytimg.com/vi/lvCNqJCattk/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDcqr-Tjntjm5wWMYhX4lhd-HdfbA',
                                     'width': 336}],
                     'title': 'My Sleeping Karma - Soma (2012) (Full Album) '
                              '(HQ)',
                     'url': 'https://www.youtube.com/watch?v=lvCNqJCattk',
                     'videoId': 'lvCNqJCattk'},
                    {'length': '3:53:24',
                     'length_human': '3 horas, 53 minutos e 24 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 94,
                                     'url': 'https://i.ytimg.com/vi/v0BhdfrBWX0/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLAZMznqs911Ek0xlUAPfbLKSCeQSQ',
                                     'width': 168},
                                    {'height': 110,
                                     'url': 'https://i.ytimg.com/vi/v0BhdfrBWX0/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLBWfhvtaj2OvyjqgMI9Nfc6XcfF5Q',
                                     'width': 196},
                                    {'height': 138,
                                     'url': 'https://i.ytimg.com/vi/v0BhdfrBWX0/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAhzz6Wn-yqxpoJI189sSAgb5QXhQ',
                                     'width': 246},
                                    {'height': 188,
                                     'url': 'https://i.ytimg.com/vi/v0BhdfrBWX0/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBLRb-UKkBD9FjcuXcKYRLvQ6P8iw',
                                     'width': 336}],
                     'title': 'Electric Octopus "Driving Under The Influence '
                              'Of Jams" (New Full Album) 2017 (Psychedelic '
                              'Rock)',
                     'url': 'https://www.youtube.com/watch?v=v0BhdfrBWX0',
                     'videoId': 'v0BhdfrBWX0'},
                    {'length': '54:01',
                     'length_human': '54 minutos e 1 segundo',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 94,
                                     'url': 'https://i.ytimg.com/vi/1SjHVDpXYgw/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDS6_z6vR9a81J0ZZXHpWIX52icQQ',
                                     'width': 168},
                                    {'height': 110,
                                     'url': 'https://i.ytimg.com/vi/1SjHVDpXYgw/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLBoVHJpZLe-x6TvgKaQKtpLTYAzvw',
                                     'width': 196},
                                    {'height': 138,
                                     'url': 'https://i.ytimg.com/vi/1SjHVDpXYgw/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAsle4LuIUaDDbDsRvCI8psmgQY7Q',
                                     'width': 246},
                                    {'height': 188,
                                     'url': 'https://i.ytimg.com/vi/1SjHVDpXYgw/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBBUUCJSVHdVQOZJyvJJtjYjLbxUA',
                                     'width': 336}],
                     'title': 'My Sleeping Karma - Moksha (2015) (Full Album)',
                     'url': 'https://www.youtube.com/watch?v=1SjHVDpXYgw',
                     'videoId': '1SjHVDpXYgw'},
                    {'length': '52:14',
                     'length_human': '52 minutos e 14 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 94,
                                     'url': 'https://i.ytimg.com/vi/kP-Xhu-T4qY/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLBnR8Fr5PH6XptB6xvgXBy6JxkqsQ',
                                     'width': 168},
                                    {'height': 110,
                                     'url': 'https://i.ytimg.com/vi/kP-Xhu-T4qY/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLCelR5ojBwj6A-_BmDdHOX5XNHj4A',
                                     'width': 196},
                                    {'height': 138,
                                     'url': 'https://i.ytimg.com/vi/kP-Xhu-T4qY/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAjZZwiaR_gboWdx0Zps5Ba3EnqDw',
                                     'width': 246},
                                    {'height': 188,
                                     'url': 'https://i.ytimg.com/vi/kP-Xhu-T4qY/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLA6NUS1e8E6deU-gRVQ6YjWkA-aaw',
                                     'width': 336}],
                     'title': 'The Re-Stoned - Stories Of The Astral '
                              'Lizard(Full Album)',
                     'url': 'https://www.youtube.com/watch?v=kP-Xhu-T4qY',
                     'videoId': 'kP-Xhu-T4qY'},
                    {'length': '1:11:28',
                     'length_human': '1 hora, 11 minutos e 28 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 94,
                                     'url': 'https://i.ytimg.com/vi/1SiZiXPa3_k/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLC2OtPY9Cm0hlMb7fu3MVTPeJ6kgA',
                                     'width': 168},
                                    {'height': 110,
                                     'url': 'https://i.ytimg.com/vi/1SiZiXPa3_k/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDV0xv2RJcFUL4cwq3SZ8RaNaadvA',
                                     'width': 196},
                                    {'height': 138,
                                     'url': 'https://i.ytimg.com/vi/1SiZiXPa3_k/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBxB7vMwmHja_uuE46SkIOdApB6WA',
                                     'width': 246},
                                    {'height': 188,
                                     'url': 'https://i.ytimg.com/vi/1SiZiXPa3_k/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDHoeU5MdiT_Im2w1Ew9rjBVpiGQA',
                                     'width': 336}],
                     'title': 'Electric Octopus - This Is Our Culture (Full '
                              'Album 2016)',
                     'url': 'https://www.youtube.com/watch?v=1SiZiXPa3_k',
                     'videoId': '1SiZiXPa3_k'},
                    {'length': '5:28',
                     'length_human': '5 minutos e 28 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 94,
                                     'url': 'https://i.ytimg.com/vi/zrz8NuALuj8/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLD6ftZ0I2ZlmDsbIbWj4OijqLKOCg',
                                     'width': 168},
                                    {'height': 110,
                                     'url': 'https://i.ytimg.com/vi/zrz8NuALuj8/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLBGn8-OvPWMuaCwF3jmCex4_SpDCQ',
                                     'width': 196},
                                    {'height': 138,
                                     'url': 'https://i.ytimg.com/vi/zrz8NuALuj8/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAgr621ZaPuH-nKW-J4qnJPOQLMAw',
                                     'width': 246},
                                    {'height': 188,
                                     'url': 'https://i.ytimg.com/vi/zrz8NuALuj8/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLC4EzQR82B4_ts9_5dLoCDCQ71bTw',
                                     'width': 336}],
                     'title': 'Pink Floyd - Marooned [HQ]',
                     'url': 'https://www.youtube.com/watch?v=zrz8NuALuj8',
                     'videoId': 'zrz8NuALuj8'},
                    {'length': '53:24',
                     'length_human': '53 minutos e 24 segundos',
                     'reason': 'Relacionado com a sua pesquisa',
                     'thumbnails': [{'height': 94,
                                     'url': 'https://i.ytimg.com/vi/-msNeB8urFI/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLBJ_DdibxyDs3sddcsW9FqIpdYndw',
                                     'width': 168},
                                    {'height': 110,
                                     'url': 'https://i.ytimg.com/vi/-msNeB8urFI/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDSJoyVQu3o-q7U3OBTRxj2ktXjMQ',
                                     'width': 196},
                                    {'height': 138,
                                     'url': 'https://i.ytimg.com/vi/-msNeB8urFI/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBAMM65qnwM5GXYFbk3MtTPE2UJ3g',
                                     'width': 246},
                                    {'height': 188,
                                     'url': 'https://i.ytimg.com/vi/-msNeB8urFI/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCDGQkRbl1GYH3BlxAAbtJME91I0g',
                                     'width': 336}],
                     'title': 'Post-Rock for Studying-Focusing',
                     'url': 'https://www.youtube.com/watch?v=-msNeB8urFI',
                     'videoId': '-msNeB8urFI'}],
 'videos': [{'length': '5:05:32',
             'length_human': '5 horas, 5 minutos e 32 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/ors0wpcVDcc/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLA-G4RJRcdkFe4WRq5E--D_5LFMTg',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/ors0wpcVDcc/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLB4fLpHcoGmPHiw22xrOvmkd-4SmA',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/ors0wpcVDcc/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBgZagtF_rt9Mz6RsB3jTxbgt8QhA',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/ors0wpcVDcc/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAQOrA5O19KW5_0xcr8BX8FKPem9A',
                             'width': 336}],
             'title': '5 Hours of Relaxing Psychedelic Space Rock - Travel Dos',
             'url': 'https://www.youtube.com/watch?v=ors0wpcVDcc',
             'videoId': 'ors0wpcVDcc'},
            {'length': '4:57:59',
             'length_human': '4 horas, 57 minutos e 59 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/iuWa5wh8lG0/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLB6ZmDC6FMxP6DS_0W5NGwnzeMt4w',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/iuWa5wh8lG0/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLBVt-u-ZPkKl1qhSggsRTI28GOs4Q',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/iuWa5wh8lG0/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBVXPkwtLUDwF-2fodagxKXs4Sp0A',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/iuWa5wh8lG0/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBd8n8EQ-M3mvU_1LHqAvBcJWbQdg',
                             'width': 336}],
             'title': '5 Hours of Relaxing Psychedelic Space Rock (I had to '
                      'mute a few tracks)',
             'url': 'https://www.youtube.com/watch?v=iuWa5wh8lG0',
             'videoId': 'iuWa5wh8lG0'},
            {'length': '4:47:37',
             'length_human': '4 horas, 47 minutos e 37 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/aaAmg9weGks/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLA-YCA2V5PqXenn9qiQsUH-3KnmQQ',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/aaAmg9weGks/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLD-WQ7OXkHVi2yoCSemuTfTBmoXPA',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/aaAmg9weGks/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLD0ang4QPFJi_no0jFVO4IUY5dvSA',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/aaAmg9weGks/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDbVrK2akHmLTbN13-uo--UcUx8kA',
                             'width': 336}],
             'title': '5 Hours of Relaxing Psychedelic Space Rock - Third Star',
             'url': 'https://www.youtube.com/watch?v=aaAmg9weGks',
             'videoId': 'aaAmg9weGks'},
            {'length': '4:57:59',
             'length_human': '4 horas, 57 minutos e 59 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/GTXXwgxQYnk/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLD2-YxCKjEAnFtOj3VRFmLqMbqCVw',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/GTXXwgxQYnk/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLCEs6Ek2JO-uBtHaoFjsdRPHEVJ0Q',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/GTXXwgxQYnk/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCZxIfeWC1Oi9cv7nj4Q7SxEeqswA',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/GTXXwgxQYnk/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAJRKprldOjfLaTeSL9xVDM0_piaA',
                             'width': 336}],
             'title': 'Relaxing Psychedelic 5 Hours of  Space RocK',
             'url': 'https://www.youtube.com/watch?v=GTXXwgxQYnk',
             'videoId': 'GTXXwgxQYnk'},
            {'length': '2:02:16',
             'length_human': '2 horas, 2 minutos e 16 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/as1QfC2L0Og/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLCYHAHPA3-Yx7CM7zsZUztp2Wu9vQ',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/as1QfC2L0Og/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLArWd_gNcVXQZYrQAahgS90vsSiMw',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/as1QfC2L0Og/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBNCxGIJsTCJkBH4HBDcluFwuumZA',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/as1QfC2L0Og/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCCB2NhoV1EbGtB6oVgGT7oK68rCA',
                             'width': 336}],
             'title': 'Psychedelic & Stoner Rock Compilation',
             'url': 'https://www.youtube.com/watch?v=as1QfC2L0Og',
             'videoId': 'as1QfC2L0Og'},
            {'length': '2:01:16',
             'length_human': '2 horas, 1 minuto e 16 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/5J6714DOVTg/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDXRESGD4hIZs0y2ZKbU5boE4IQ8g',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/5J6714DOVTg/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLAldzXwitPAJNz9mFmYdeWfl9djVQ',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/5J6714DOVTg/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLC-D5Lu_s9Owpg6LAh92hTZ4DPMvg',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/5J6714DOVTg/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLA_e3up6aMpRM5ShB9rzgrYQcloLw',
                             'width': 336}],
             'title': 'Feed Your Space Head  14  A Space Rock/Psychedelic mix',
             'url': 'https://www.youtube.com/watch?v=5J6714DOVTg',
             'videoId': '5J6714DOVTg'},
            {'length': '35:56',
             'length_human': '35 minutos e 56 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/EDpXcVrI4xQ/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDR7mpwZy5dOXpPbKPpFidVXUbugw',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/EDpXcVrI4xQ/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDLndQ2qwf6r0-jfGpyNy51CdBACg',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/EDpXcVrI4xQ/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCeuDG5XYohqjFAMYn3ekO39evV5A',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/EDpXcVrI4xQ/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBvGsk8G2AtHr7RstCvWbdfYeMc6A',
                             'width': 336}],
             'title': 'Yuri Gagarin - Yuri Gagarin (2013) (Space Rock)',
             'url': 'https://www.youtube.com/watch?v=EDpXcVrI4xQ',
             'videoId': 'EDpXcVrI4xQ'},
            {'length': '2:02:50',
             'length_human': '2 horas, 2 minutos e 50 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/0C_69F7eLhc/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLAeJM5MOw6G7bqzzgOj_eHpKnC9xw',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/0C_69F7eLhc/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLAdvVIkietsR_wV-iS-pIQuP8YkWQ',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/0C_69F7eLhc/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLC3TUEexb4wqdLw7SKhKh4xD8oYmQ',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/0C_69F7eLhc/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAQu-sHlVTmSU6NNMe7aGeT_kh8mg',
                             'width': 336}],
             'title': 'Psychedelic Stoner Rock Mix #2',
             'url': 'https://www.youtube.com/watch?v=0C_69F7eLhc',
             'videoId': '0C_69F7eLhc'},
            {'length': '5:05:32',
             'length_human': '5 horas, 5 minutos e 32 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/jsqXyK2Yp1s/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLCnfZquHQ9JREu6rrb5z67QHVTpUQ',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/jsqXyK2Yp1s/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLD9G_ke78WTkFeRic3pws1fRL47vw',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/jsqXyK2Yp1s/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBOosgQ3oLsAO1rt2Dr_OrI4hEOOg',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/jsqXyK2Yp1s/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBIxytUwaJAxC_S152ypqvABsp4KA',
                             'width': 336}],
             'title': '5 Hours of Relaxing Psychedelic Space Rock - Trave',
             'url': 'https://www.youtube.com/watch?v=jsqXyK2Yp1s',
             'videoId': 'jsqXyK2Yp1s'},
            {'length': '3:15',
             'length_human': '3 minutos e 15 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/Tu5i9mXCn0k/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDVZzuZk--PcLNshyfilOLq9euUyA',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/Tu5i9mXCn0k/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDq_dop44sr27EDC92Hm5vY7fXVvg',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/Tu5i9mXCn0k/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCBN_2ae3zO7Qna-jFa8QO2anttZw',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/Tu5i9mXCn0k/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDnFxcTeIK2H2lMzm2LSUItPpmxnw',
                             'width': 336}],
             'title': 'POWERCYAN - Space Rock (PYLOT remix)',
             'url': 'https://www.youtube.com/watch?v=Tu5i9mXCn0k',
             'videoId': 'Tu5i9mXCn0k'},
            {'length': '38:19',
             'length_human': '38 minutos e 19 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/WAQofc7nEks/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLAYQ_okNiy5cs38B54aBUdQfLCt4g',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/WAQofc7nEks/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLBwXppC-bGKxGXMD0XU5StJleikYQ',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/WAQofc7nEks/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAaDndFFBWWxGp9lRla44Yb9MCGlA',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/WAQofc7nEks/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAtTyN_z86ZljP3T_bX-sVfx4jRtQ',
                             'width': 336}],
             'title': 'Space Rock/ Psych rock mix',
             'url': 'https://www.youtube.com/watch?v=WAQofc7nEks',
             'videoId': 'WAQofc7nEks'},
            {'length': '5:04:19',
             'length_human': '5 horas, 4 minutos e 19 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/VlUK6Gq9CyY/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLBLkAhX_xNPoDtjtmD90rWGmPBptA',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/VlUK6Gq9CyY/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDwUPpHiDxvx9XE7eWTfNjweXq_5Q',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/VlUK6Gq9CyY/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLC7AWVu8LlGKMC3tJeOdXwN_jK3yg',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/VlUK6Gq9CyY/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBYMLcQejbVb2ubE1MB-a1KJF9zHg',
                             'width': 336}],
             'title': 'Five Hours Of Instrumental Post-rock (The Best Of 2018)',
             'url': 'https://www.youtube.com/watch?v=VlUK6Gq9CyY',
             'videoId': 'VlUK6Gq9CyY'},
            {'length': '33:07',
             'length_human': '33 minutos e 7 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/icgGyR3iusU/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDdQb246KEjAd8ds4dW6w-Vb2nXNw',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/icgGyR3iusU/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLA4phAgAA4HvxxPSs5eaaF2NArvwg',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/icgGyR3iusU/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCCyC-fC-sM-PCEppolz8xtj_aC2Q',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/icgGyR3iusU/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCKomn6fCTgBiMWYno7NPvu_742BQ',
                             'width': 336}],
             'title': 'Epic Space Music Mix | Most Beautiful & Emotional Music '
                      '| SG Music',
             'url': 'https://www.youtube.com/watch?v=icgGyR3iusU',
             'videoId': 'icgGyR3iusU'},
            {'length': '2:37:24',
             'length_human': '2 horas, 37 minutos e 24 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/jNYD1IzSXwA/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLC4G3BIzK2K_uM1a593sEKZ1YX1RQ',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/jNYD1IzSXwA/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLBPmNYpN5-xV-ZTvgZ1qB6ZkLCbyg',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/jNYD1IzSXwA/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDx1eRuBidX_R34hhwE9Dmt2BisMA',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/jNYD1IzSXwA/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBh0WuQGo1CiID2o6prG3L1yKo2Ow',
                             'width': 336}],
             'title': '2.5 Hours of Instrumental Psychedelic/Stoner Rock',
             'url': 'https://www.youtube.com/watch?v=jNYD1IzSXwA',
             'videoId': 'jNYD1IzSXwA'},
            {'length': '1:22:10',
             'length_human': '1 hora, 22 minutos e 10 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/D0wSiKOY6dA/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDCmOeV9g_R-hLI8KRChcFOre9Suw',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/D0wSiKOY6dA/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLAWrHhcYo_22p_0EZ2xOzEqIBrFFQ',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/D0wSiKOY6dA/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLD_GpKohyOUjbgiA0xylypkqT7sgA',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/D0wSiKOY6dA/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLB804a2tLTl0mkQ64NGb3DNzQ9NTQ',
                             'width': 336}],
             'title': 'Instrumental Post-rock Compilation',
             'url': 'https://www.youtube.com/watch?v=D0wSiKOY6dA',
             'videoId': 'D0wSiKOY6dA'},
            {'length': '1:05:34',
             'length_human': '1 hora, 5 minutos e 34 segundos',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/ZpCluchEflg/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLD22wU-2S5J9Nj5ZdbulDZ--aw2bQ',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/ZpCluchEflg/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDvoWuG7w9yFRpWV4mn-T3afP7bYQ',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/ZpCluchEflg/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBXWpJiyLDLPr1JFnHrKOizVGflTA',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/ZpCluchEflg/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLClk_IKJi7sfJRyBqxId5ful8syRg',
                             'width': 336}],
             'title': 'Best Of Melancholic Post-Rock Mix',
             'url': 'https://www.youtube.com/watch?v=ZpCluchEflg',
             'videoId': 'ZpCluchEflg'},
            {'length': '51:01',
             'length_human': '51 minutos e 1 segundo',
             'thumbnails': [{'height': 94,
                             'url': 'https://i.ytimg.com/vi/1Ea4zENTZlQ/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLBu9h8bRp8Jd9VF3mePZN_RTFva9w',
                             'width': 168},
                            {'height': 110,
                             'url': 'https://i.ytimg.com/vi/1Ea4zENTZlQ/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDmGmaRBLU9LWGprUjNV1mk4p1pxw',
                             'width': 196},
                            {'height': 138,
                             'url': 'https://i.ytimg.com/vi/1Ea4zENTZlQ/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLATtRrFGvA7T8ZaReAm6UD26WlxgA',
                             'width': 246},
                            {'height': 188,
                             'url': 'https://i.ytimg.com/vi/1Ea4zENTZlQ/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAJXU5mQRLxLxm3ZqoKKy8SoRmyfQ',
                             'width': 336}],
             'title': 'Mantra Machine "Nitrogen" (Full Album) 2014 '
                      'Instrumental Stoner/Space Rock',
             'url': 'https://www.youtube.com/watch?v=1Ea4zENTZlQ',
             'videoId': '1Ea4zENTZlQ'}]}

"""